[package]
name = "naive-rsa"
edition = "2021"
authors = "Tristan"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

num-bigint = "0.4.4"
num-traits = "0.2.16"
rand = "0.8.5"
num-integer = "0.1.45"
